In [4]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [5]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [16]:
print(arr2.ndim)
print(arr2.size)
print(arr2.shape)
print(arr2.dtype)

2
6
(2, 3)
int64


In [12]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(arr3)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [9]:
arr4=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(arr4)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [1]:
import numpy as np


In [2]:
np.__version__

'2.2.2'

In [3]:
np.show_config()

{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-fwtr2gmz/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib direct

c:\Users\upend\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [8]:
a=np.array(10)
print(a)
print(a.ndim)
print(a.size)
print(a.shape)

10
0
1
()


In [9]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [21]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [23]:
print(a[1][0])
print(a[0][0])

4
1


In [27]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(a)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [30]:
a=[10,20,30]
b=np.array(a,dtype=float)
print(b)

[10. 20. 30.]


In [31]:
a=[[10,20,30],[40,50,60]]
b=np.array(a,dtype=int,order='C')
print(b)


[[10 20 30]
 [40 50 60]]


In [33]:
for i in np.nditer(b):
    print(i)

10
20
30
40
50
60


In [34]:
a=[[10,20,30],[40,50,60]]
b=np.array(a,dtype=int,order='F')

for i in np.nditer(b):
    print(i)

10
40
20
50
30
60


In [37]:
a=b"welcome to numpy"
b=np.frombuffer(a,dtype='S1' ,count=3,offset=2)
print(b)

[b'l' b'c' b'o']


In [43]:
a=[10,20,30,40,50]
b=np.fromiter(a,dtype=int,count=3)
print(b)

[10 20 30]


In [46]:
a=np.zeros(3)
print(a)
b=np.zeros((3,3))

[0. 0. 0.]
